server:
  port: 2025


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DevRooster/RS-CT.git # ruta del repositorio git / repositorio
          searchPaths: config-data  
          #username:
          #password:
          default-label: main # Rama del repositorio



  #Seguridad de config-server
  security:
    user:
      name: root
      password: 202501
