server:
  port: 2025


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DevRooster/RS-CT.git # ruta del repositorio git
          searchPaths: config-data
          #username:
          #password:
          default-label: main




  security:
    user:
      name: root
      password: 202501
